name: Ghongflix
title: Ghongflix | A blog for studying development
description: blog for studying computer science, data, algorithm and all related developments.
tags:
  - C language
  - C++
  - C#
  - docker
  - algorithm
  - 42seoul
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: geunyeonghong@gmail.com
disqus_username: geunyeonghong
